INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (2, 'ivysaur', 'stage-1', '3', 'grass', 'poison', 'When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/2.gif', 5000, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (3, 'venusaur', 'stage-2', null, 'grass', 'poison', 'The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/3.gif', null, 0.5);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (4, 'charmander', 'basic', '5', 'fire', null, 'Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/4.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (5, 'charmeleon', 'stage-1', '6', 'fire', null, 'When it swings its burning tail, it elevates the temperature to unbearably high levels.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/5.gif', 5000, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (6, 'charizard', 'stage-1', null, 'fire', 'flying', 'Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/6.gif', null, 0.5);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (7, 'squirtle', 'basic', '8', 'water', null, 'After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/7.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (8, 'wartortle', 'stage-1', '9', 'water', null, 'Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/8.gif', 5000, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (9, 'blastoise', 'stage-2', null, 'water', null, 'A brutal POKéMON with pressurized water jets on its shell. They are used for high speed tackles.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/9.gif', null, 0.5);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (10, 'caterpie', 'basic', '11', 'bug', null, '如果碰到牠頭上的觸角， 牠就會分泌強烈的臭味 來保護自己。', 'bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/10.gif', 2000, 0.1);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (11, 'metapod', 'stage-1', '12', 'bug', null, 'This POKéMON is vulnerable to attack while its shell is soft, exposing its weak and tender body.', 'bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/11.gif', 4000, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (12, 'butterfree', 'stage-2', null, 'bug', 'flying', 'In battle, it flaps its wings at high speed to release highly toxic dust into the air.', 'bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/12.gif', null, 0.4);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (13, 'weedle', 'basic', '14', 'bug', 'poison', 'Often found in forests, eating leaves. It has a sharp venomous stinger on its head.', 'bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/13.gif', 2000, 0.1);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (14, 'kakuna', 'stage-1', '15', 'bug', 'poison', 'Almost incapable of moving, this POKéMON can only harden its shell to protect itself from predators.', 'bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/14.gif', 4000, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (15, 'beedrill', 'stage-2', null, 'bug', 'poison', 'It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly.', 'bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/15.gif', null, 0.4);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (16, 'pidgey', 'basic', '17', 'normal', 'flying', 'A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/16.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (17, 'pidgeotto', 'stage-1', '18', 'normal', 'flying', 'Very protective of its sprawling territorial area, this POKéMON will fiercely peck at any intruder.', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/17.gif', 5000, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (18, 'pidgeot', 'stage-2', null, 'normal', 'flying', 'When hunting, it skims the surface of water at high speed to pick off unwary prey such as MAGIKARP.', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/18.gif', null, 0.5);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (19, 'rattata', 'basic', '12', 'normal', null, 'キバが２つ。とにかく　なんでも かじってみる。１ぴき　みつけたら ４０ぴきは　そこに　すんでるはず。', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/19.gif', 3000, 0.1);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (20, 'raticate', 'stage-1', null, 'normal', null, 'Ses pattes arrière lui permettent de traverser les rivières. Il est toujours en quête de nourriture.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/20.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (21, 'spearow', 'basic', '22', 'normal', 'flying', 'It flaps its small wings busily to fly. Using its beak, it searches in grass for prey.', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/21.gif', 4000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (22, 'fearow', 'stage-1', null, 'normal', 'flying', 'With its huge and magnificent wings, it can keep aloft without ever having to land for rest.', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/22.gif', null, 0.4);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (23, 'ekans', 'basic', '24', 'poison', null, 'Moves silently and stealthily. Eats the eggs of birds, such as PIDGEY and SPEAROW, whole.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/23.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (24, 'arbok', 'stage-1', null, 'poison', null, 'It is rumored that the ferocious warning markings on its belly differ from area to area.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/24.gif', null, 0.4);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (25, 'pikachu', 'basic', '26', 'electric', null, 'When several of these POKéMON gather, their electricity could build and cause lightning storms.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/25.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (26, 'raichu', 'stage-1', null, 'electric', null, 'Its long tail serves as a ground to protect itself from its own high-voltage power.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/26.gif', null, 0.4);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (27, 'sandshrew', 'basic', '28', 'ground', null, 'Burrows deep underground in arid locations far from water. It only emerges to hunt for food.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/27.gif', 4000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (28, 'sandslash', 'stage-1', null, 'ground', null, 'Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/28.gif', null, 0.4);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (29, 'nidoran-f', 'basic', '30', 'poison', null, 'Although small, its venomous barbs render this POKéMON dangerous. The female has smaller horns.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/29.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (30, 'nidorina', 'stage-1', '31', 'poison', null, 'The female''s horn develops slowly. Prefers physical attacks such as clawing and biting.', 'no-eggs', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/30.gif', 5000, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (31, 'nidoqueen', 'stage-2', null, 'poison', 'ground', 'Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves.', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/31.gif', null, 0.5);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (32, 'nidoran-m', 'basic', '33', 'poison', null, 'Stiffens its ears to sense danger. The larthe fluidger its horns, the more powerful its secreted venom.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/32.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (33, 'nidorino', 'stage-1', '34', 'poison', null, '神經質且容易發脾氣打架。 當體內的腎上腺素增加時， 毒素的濃度也會提升。', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/33.gif', 5000, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (34, 'nidoking', 'stage-2', null, 'poison', 'ground', 'It uses its powerful tail in battle to smash, constrict, then break the prey''s bones.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/34.gif', null, 0.5);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (35, 'clefairy', 'basic', '36', 'fairy', null, 'Its magical and cute appeal has many admirers. It is rare and found only in certain areas.', 'fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/35.gif', 4000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (36, 'clefable', 'stage-1', null, 'fairy', null, 'A timid fairy POKéMON that is rarely seen. It will run and hide the moment it senses people.', 'fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/36.gif', null, 0.4);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (37, 'vulpix', 'basic', '38', 'fire', null, 'At the time of birth, it has just one tail. The tail splits from its tip as it grows older.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/37.gif', 3000, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (38, 'ninetales', 'stage-1', null, 'fire', null, 'Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/38.gif', null, 0.4);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (39, 'jigglypuff', 'basic', '40', 'normal', 'fairy', 'When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.', 'fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/39.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (40, 'wigglytuff', 'stage-1', null, 'normal', 'fairy', 'The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size.', 'fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/40.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (41, 'zubat', 'basic', '42', 'poison', 'flying', '因為沒有眼珠所以看不見東西。 會從口中發出超音波 來探測 周圍的狀況。', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/41.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (42, 'golbat', 'stage-1', null, 'poison', 'flying', 'Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/42.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (43, 'oddish', 'basic', '44', 'grass', 'poison', 'During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.', 'plant', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/43.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (44, 'gloom', 'stage-1', '45', 'grass', 'poison', 'The fluid that oozes from its mouth isn''t drool. It is a nectar that is used to attract prey.', 'plant', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/44.gif', 5000, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (45, 'vileplume', 'stage-2', null, 'grass', 'poison', 'It has the world''s largest petals. With every step, the petals shake out heavy clouds of toxic pollen.', 'plant', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/45.gif', null, 0.5);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (46, 'paras', 'basic', '47', 'bug', 'grass', 'Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host.', 'bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/46.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (47, 'parasect', 'stage-1', null, 'bug', 'grass', 'A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places.', 'bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/47.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (48, 'venonat', 'basic', '49', 'bug', 'poison', 'Lives in the shadows of tall trees where it eats insects. It is attracted by light at night.', 'bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/48.gif', null, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (49, 'venomoth', 'stage-1', null, 'bug', 'poison', 'The dustlike scales covering its wings are color-coded to indicate the kinds of poison it has.', 'bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/49.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (50, 'diglett', 'basic', '51', 'ground', null, '피부가 매우 얇아서 빛을 쪼이게 되면 혈액이 데워져 약해 진다.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/50.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (51, 'dugtrio', 'stage-1', null, 'ground', null, 'A team of DIGLETT triplets. It triggers huge earthquakes by burrowing 60 miles underground.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/51.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (52, 'meowth', 'basic', '53', 'normal', null, 'It washes its face regularly to keep the coin on its forehead spotless. It doesn’t get along with Galarian Meowth.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/52.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (53, 'persian', 'stage-1', null, 'normal', null, 'Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/53.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (54, 'psyduck', 'basic', '55', 'water', null, 'While lulling its enemies with its vacant look, this wily POKéMON will use psychokinetic powers.', 'water1', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/54.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (55, 'golduck', 'stage-1', null, 'water', null, 'Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa.', 'water1', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/55.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (56, 'mankey', 'basic', '57', 'fighting', null, 'Extremely quick to anger. It could be docile one moment then thrashing away the next instant.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/56.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (57, 'primeape', 'stage-1', null, 'fighting', null, 'Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/57.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (58, 'growlithe', 'basic', '59', 'fire', null, 'Very protective of its territory. It will bark and bite to repel intruders from its space.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/58.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (59, 'arcanine', 'stage-1', null, 'fire', null, 'A POKéMON that has been admired since the past for its beauty. It runs agilely as if on wings.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/59.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (60, 'poliwag', 'basic', '61', 'water', null, 'Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand.', 'water1', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/60.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (61, 'poliwhirl', 'stage-1', '62', 'water', null, 'Capable of living in or out of water. When out of water, it sweats to keep its body slimy.', 'water1', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/61.gif', 5000, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (62, 'poliwrath', 'stage-2', null, 'water', 'fighting', 'An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers.', 'water1', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/62.gif', null, 0.5);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (63, 'abra', 'basic', '64', 'psychic', null, 'Using its ability to read minds, it will identify impending danger and TELEPORT to safety.', 'humanshape', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/63.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (64, 'kadabra', 'stage-1', '65', 'psychic', null, 'It emits special alpha waves from its body that induce headaches just by being close by.', 'humanshape', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/64.gif', 5000, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (65, 'alakazam', 'stage-2', null, 'psychic', null, 'Its brain can out perform a super computer. Its intelligence quotient is said to be 5,000.', 'humanshape', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/65.gif', null, 0.5);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (66, 'machop', 'basic', '67', 'fighting', null, 'Malgré sa petite taille, sa force lui permet de soulever plusieurs Racaillou à la fois.', 'humanshape', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/66.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (67, 'machoke', 'stage-1', '68', 'fighting', null, 'Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions.', 'humanshape', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/67.gif', 5000, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (68, 'machamp', 'stage-2', null, 'fighting', null, 'Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon.', 'humanshape', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/68.gif', null, 0.5);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (69, 'bellsprout', 'basic', '70', 'grass', 'poison', 'A carnivorous POKéMON that traps and eats bugs. It uses its root feet to soak up needed moisture.', 'plant', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/69.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (70, 'weepinbell', 'stage-1', '71', 'grass', 'poison', 'It spits out POISONPOWDER to immobilize the enemy and then finishes it with a spray of ACID.', 'plant', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/70.gif', 5000, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (71, 'victreebel', 'stage-2', null, 'grass', 'poison', 'Dieses Pokémon soll in großen Kolonien tief im Dschungel leben, doch niemand kann dies bestätigen.', 'plant', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/71.gif', null, 0.5);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (72, 'tentacool', 'basic', '73', 'water', 'poison', 'Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid.', 'water3', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/72.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (73, 'tentacruel', 'stage-1', null, 'water', 'poison', 'The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.', 'water3', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/73.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (74, 'geodude', 'basic', '75', 'rock', 'ground', 'Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.', 'mineral', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/74.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (75, 'graveler', 'stage-1', '76', 'rock', 'ground', 'De naturaleza descuidada y libre, no le importa dañarse cuando baja rodando montañas.', 'mineral', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/75.gif', 5000, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (76, 'golem', 'stage-2', null, 'rock', 'ground', 'Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.', 'mineral', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/76.gif', null, 0.5);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (77, 'ponyta', 'basic', '78', 'fire', null, 'Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/77.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (78, 'rapidash', 'stage-1', null, 'fire', null, 'Galopa a casi 240 km por hora. Su crin ardiente parece una flecha cuando corre.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/78.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (79, 'slowpoke', 'basic', '80', 'water', 'psychic', 'Descansa ocioso junto al agua. Si algo muerde su cola, no lo notará en todo el día.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/79.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (80, 'slowbro', 'stage-1', null, 'water', 'psychic', 'The SHELLDER that is latched onto SLOWPOKE''s tail is said to feed on the host''s left over scraps.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/80.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (81, 'magnemite', 'basic', '82', 'electric', 'steel', 'Uses anti-gravity to stay suspended. Appears without warning and uses THUNDER WAVE and similar moves.', 'mineral', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/81.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (82, 'magneton', 'stage-1', null, 'electric', 'steel', 'Formed by several MAGNEMITEs linked together. They frequently appear when sunspots flare up.', 'mineral', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/82.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (83, 'farfetchd', 'basic', null, 'normal', 'flying', 'The sprig of green onions it holds is its weapon. It is used much like a metal sword.', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/83.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (84, 'doduo', 'basic', '85', 'normal', 'flying', 'A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints.', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/84.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (85, 'dodrio', 'stage-1', null, 'normal', 'flying', '由嘟嘟的某个头分裂 出的变种。以60千米的 时速在草原上奔跑。', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/85.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (86, 'seel', 'basic', '87', 'water', null, 'The protruding horn on its head is very hard. It is used for bashing through thick ice.', 'water1', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/86.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (87, 'dewgong', 'stage-1', null, 'water', 'ice', 'Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters.', 'water1', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/87.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (88, 'grimer', 'basic', '89', 'poison', null, 'Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories.', 'indeterminate', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/88.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (89, 'muk', 'stage-1', null, 'poison', null, 'Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison.', 'indeterminate', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/89.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (90, 'shellder', 'basic', '91', 'water', null, 'Its hard shell repels any kind of attack. It is vulnerable only when its shell is open.', 'water3', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/90.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (91, 'cloyster', 'stage-1', null, 'water', 'ice', 'When attacked, it launches its horns in quick volleys. Its innards have never been seen.', 'water3', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/91.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (92, 'gastly', 'basic', '93', 'ghost', 'poison', 'Almost invisible, this gaseous POKéMON cloaks the target and puts it to sleep without notice.', 'indeterminate', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/92.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (93, 'haunter', 'stage-1', '94', 'ghost', 'poison', 'Because of its ability to slip through block walls, it is said to be from an other dimension.', 'indeterminate', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/93.gif', 5000, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (94, 'gengar', 'stage-2', null, 'ghost', 'poison', 'Under a full moon, this POKéMON likes to mimic the shadows of people and laugh at their fright.', 'indeterminate', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/94.gif', null, 0.5);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (95, 'onix', 'basic', null, 'rock', 'ground', 'As it grows, the stone portions of its body harden to become similar to a diamond, but colored black.', 'mineral', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/95.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (96, 'drowzee', 'basic', '97', 'psychic', null, 'Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams.', 'humanshape', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/96.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (97, 'hypno', 'stage-1', null, 'psychic', null, 'When it locks eyes with an enemy, it will use a mix of PSI moves such as HYPNOSIS and CONFUSION.', 'humanshape', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/97.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (98, 'krabby', 'basic', '99', 'water', null, 'Its pincers are not only powerful weapons, they are used for balance when walking sideways.', 'water3', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/98.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (99, 'kingler', 'stage-1', null, 'water', null, 'The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use.', 'water3', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/99.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (100, 'voltorb', 'basic', '101', 'electric', null, 'Usually found in power plants. Easily mistaken for a POKé BALL, they have zapped many people.', 'mineral', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/100.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (101, 'electrode', 'stage-1', null, 'electric', null, 'It stores electric energy under very high pressure. It often explodes with little or no provocation.', 'mineral', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/101.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (102, 'exeggcute', 'basic', '103', 'grass', 'psychic', 'Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms.', 'plant', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/102.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (103, 'exeggutor', 'stage-1', null, 'grass', 'psychic', 'Legend has it that on rare occasions, one of its heads will drop off and continue on as an EXEGGCUTE.', 'plant', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/103.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (104, 'cubone', 'basic', '105', 'ground', null, 'Because it never removes its skull helmet, no one has ever seen this POKéMON''s real face.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/104.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (105, 'marowak', 'stage-1', null, 'ground', null, '将骨头像回力镖一样扔出去， 击落天敌秃鹰娜来复仇。', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/105.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (106, 'hitmonlee', 'basic', null, 'fighting', null, 'When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides.', 'humanshape', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/106.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (107, 'hitmonchan', 'basic', null, 'fighting', null, 'While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see.', 'humanshape', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/107.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (108, 'lickitung', 'basic', null, 'normal', null, 'Its tongue can be extended like a chameleon''s. It leaves a tingling sensation when it licks enemies.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/108.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (109, 'koffing', 'basic', '110', 'poison', null, 'Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.', 'indeterminate', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/109.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (110, 'weezing', 'stage-1', null, 'poison', null, 'Where two kinds of poison gases meet, 2 KOFFINGs can fuse into a WEEZING over many years.', 'indeterminate', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/110.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (111, 'rhyhorn', 'basic', '112', 'ground', 'rock', 'A POKéMON with a one-track mind. Once it charges,  it won''t stop running until it falls asleep.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/111.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (112, 'rhydon', 'stage-1', null, 'ground', 'rock', 'Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/112.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (113, 'chansey', 'basic', null, 'normal', null, 'A rare and elusive POKéMON that is said to bring happiness to those who manage to get it.', 'fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/113.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (114, 'tangela', 'basic', null, 'grass', null, 'The whole body is swathed with wide vines that are similar to sea weed. Its vines shake as it walks.', 'plant', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/114.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (115, 'kangaskhan', 'basic', null, 'normal', null, 'The infant rarely ventures out of its mother''s protective pouch until it is 3 years old.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/115.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (116, 'horsea', 'basic', '117', 'water', null, 'Known to shoot down flying bugs with precision blasts of ink from the surface of the water.', 'water1', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/116.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (117, 'seadra', 'stage-1', null, 'water', null, 'Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail.', 'water1', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/117.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/117.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (118, 'goldeen', 'basic', '119', 'water', null, 'Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen.', 'water2', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/118.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (119, 'seaking', 'stage-1', null, 'water', null, 'In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks.', 'water2', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/119.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/119.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (120, 'staryu', 'basic', '121', 'water', null, 'If its body is torn, it can grow back if the red core remains. The core flashes at midnight.', 'water3', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/120.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (121, 'starmie', 'stage-1', null, 'water', 'psychic', 'Its central core glows with the seven colors of the rainbow. Some people value the core as a gem.', 'water3', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/121.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (122, 'mr-mime', 'basic', null, 'psychic', 'fairy', 'If interrupted while it is miming, it will slap around the offender with its broad hands.', 'humanshape', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/122.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (123, 'scyther', 'basic', null, 'bug', 'flying', 'With ninja-like agility and speed, it can create the illusion that there is more than one.', 'bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/123.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (124, 'jynx', 'basic', null, 'ice', 'psychic', 'It seductively wiggles its hips as it walks. It can cause people to dance in unison with it.', 'humanshape', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/124.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (125, 'electabuzz', 'basic', null, 'electric', null, 'Normally found near power plants, they can wander away and cause major blackouts in cities.', 'humanshape', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/125.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (126, 'magmar', 'basic', null, 'fire', null, 'Its body always burns with an orange glow that enables it to hide perfectly among flames.', 'humanshape', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/126.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (127, 'pinsir', 'basic', null, 'bug', null, 'If it fails to crush the victim in its pincers, it will swing it around and toss it hard.', 'bug', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/127.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (128, 'tauros', 'basic', null, 'normal', null, 'When it targets an enemy, it charges furiously while whipping its body with its long tails.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/128.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (129, 'magikarp', 'basic', '130', 'water', null, 'In the distant past, it was somewhat stronger than the horribly weak descendants that exist today.', 'water2', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/129.gif', 5000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (130, 'gyarados', 'stage-1', null, 'water', 'flying', 'Once it begins to rampage, a GYARADOS will burn everything down, even in a harsh storm.', 'water2', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/130.gif', null, 0.4);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (131, 'lapras', 'basic', null, 'water', 'ice', 'A POKéMON that has been over hunted almost to extinction. It can ferry people across the water.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/131.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (132, 'ditto', 'basic', null, 'normal', null, 'Capable of copying an enemy''s genetic code to instantly transform itself into a duplicate of the enemy.', 'ditto', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/132.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (133, 'eevee', 'basic', null, 'normal', null, 'Its genetic code is irregular. It may mutate if it is exposed to radiation from element STONEs.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/133.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (134, 'vaporeon', 'stage-1', null, 'water', null, 'Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid''s.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/134.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (135, 'jolteon', 'stage-1', null, 'electric', null, 'It accumulates negative ions in the atmosphere to blast out 10000- volt lightning bolts.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/135.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (136, 'flareon', 'stage-1', null, 'fire', null, 'When storing thermal energy in its body, its temperature could soar to over 1600 degrees.', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/136.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (137, 'porygon', 'basic', null, 'normal', null, 'A POKéMON that consists entirely of programming code. Capable of moving freely in cyberspace.', 'mineral', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/137.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (138, 'omanyte', 'basic', '139', 'rock', 'water', 'Although long extinct, in rare cases, it can be genetically resurrected from fossils.', 'water1', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/138.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (139, 'omastar', 'stage-1', '139', 'rock', 'water', 'A prehistoric POKéMON that died out when its heavy shell made it impossible to catch prey.', 'water1', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/139.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (140, 'kabuto', 'basic', '141', 'rock', 'water', 'A POKéMON that was resurrected from a fossil found in what was once the ocean floor eons ago.', 'water1', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/140.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (141, 'kabutops', 'stage-1', null, 'rock', 'water', 'È un perfetto nuotatore. Taglia la preda con le sue falci e ne succhia il sangue.', 'water1', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/141.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (142, 'aerodactyl', 'basic', null, 'rock', 'flying', 'A Pokémon that roamed the skies in the dinosaur era. Its teeth are like saw blades.', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/142.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (143, 'snorlax', 'basic', null, 'normal', null, 'Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.', 'monster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/143.gif', null, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (144, 'articuno', 'legend', null, 'ice', 'flying', 'A legendary bird POKéMON that is said to appear to doomed people who are lost in icy mountains.', 'no-eggs', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/144.gif', null, 1);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (145, 'zapdos', 'legend', null, 'electric', 'flying', 'かみなりぐもの　なかに　いると いわれる　でんせ つの　ポケモン。 カミナリを　じざいに　あやつる。', 'no-eggs', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/145.gif', null, 1);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (146, 'moltres', 'legend', null, 'fire', 'flying', 'Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames.', 'no-eggs', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/146.gif', null, 1);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (147, 'dratini', 'basic', '148', 'dragon', null, 'Long considered a mythical POKéMON until recently when a small colony was found living underwater.', 'water1', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/147.gif', 3000, 0.2);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (148, 'dragonair', 'stage-1', '149', 'dragon', null, '人们相信它能操纵天气， 所以在哈克龙栖息的湖里，  供品总是源源不断。', 'water1', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/148.gif', 5000, 0.3);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (149, 'dragonite', 'stage-2', null, 'dragon', 'flying', 'An extremely rarely seen marine POKéMON. Its intelligence is said to match that of humans.', 'water1', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/149.gif', null, 0.5);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (150, 'mewtwo', 'legend', null, 'psychic', null, 'It was created by a scientist after years of horrific gene splicing and DNA engineering experiments.', 'no-eggs', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/150.gif', null, 1);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (151, 'mew', 'legend', null, 'psychic', null, 'So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide.', 'no-eggs', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/151.gif', null, 1);
INSERT INTO pokedex (dex_id, name, evo_stage, evo_pokemon, type_1, type_2, description, egg_group, img_link, gif_link, exp_required, currency_pm)
        VALUES (10000, 'egg', 'egg', null, 'egg', null, 'It''s an egg. I wonder what''s inside', null, 'https://archives.bulbagarden.net/media/upload/archive/e/ed/20170805233207%21Spr_5b_Egg.png', 'https://archives.bulbagarden.net/media/upload/4/45/Spr_4d_Egg.png', 1000, 0);